name = input("Nhập họ và tên: ")
tuoi = int(input("Nhập tuổi: "))
gt = input("Nhập giới tính: ")
rp = input("Nhập tình trạng hôn nhân: ")
print("Họ và tên: ", name)
print("Tuổi: ", tuoi)
print("Giới tính: ", gt)
print("Tình trạng hôn nhân: ", rp)